---
- name: Install epel and elrepo repositories
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - repo_epel_task.yml
    - repo_elrepo_task.yml

- name: Install hardware management and monitoring tools - EL7
  ansible.builtin.yum:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - smartmontools
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - ipset
      - ipset-service
      - ipmitool
      - nvme-cli
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - smartmontools
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - iproute-tc
      - ipset
      - ipset-service
      - ipmitool
      - nvme-cli
    state: present
    update_cache: false
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Install from pip the jc module
  ansible.builtin.pip:
    executable: pip3
    name:
      - jc==1.22.1
    extra_args: --user
    state: present

- name: Enable and start cron
  ansible.builtin.systemd:
    name: crond
    state: restarted
    enabled: true

