---
- name: Install hardware management and monitoring tools - CENTOS
  ansible.builtin.yum:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - smartmontools
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - smartmontools
    state: present
    update_cache: false
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Install hardware management and monitoring tools - CENTOS
  ansible.builtin.yum:
    name:
      - ipmitool
    state: present
    enablerepo: "epel"
  when:
    - ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
    - ansible_facts['ansible_ipmi'] is defined and ansible_facts['ansible_ipmi']
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - ipmitool
    state: present
    enablerepo: "epel"
  when:
    - ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
    - ansible_facts['ansible_ipmi'] is defined and ansible_facts['ansible_ipmi']
  tags: packages

- name: Install from pip the jc module
  ansible.builtin.pip:
    executable: pip3
    name:
      - jc==1.22.1
    extra_args: --user
    state: present
