---
- include_tasks: repo_epel_task.yml

- name: Install hardware management and monitoring tools - CENTOS
  ansible.builtin.yum:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - hwloc
      - hwloc-plugins
      - numactl
      - libcgroup-tools
      - libcgroup
      - smartmontools
    state: latest
    update_cache: true
    enablerepo: "epel"
  when: ansible_facts['distribution'] == 'CentOS'
  tags: packages

- name: Install hardware management and monitoring tools - CENTOS
  ansible.builtin.yum:
    name:
      - ipmitool
    state: latest
    enablerepo: "epel"
  when: ansible_facts['ansible_ipmi'] is defined and ansible_facts['ansible_ipmi']
  tags: packages

- name: Install hardware management and monitoring tools - Fedora
  ansible.builtin.dnf:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - hwloc
      - hwloc-plugins
      - numactl
      - libcgroup-tools
      - libcgroup
      - smartmontools
    state: latest
    update_cache: true
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

