---
- name: Install hardware management and monitoring tools - EL7
  ansible.builtin.yum:
    name:
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - smartmontools
      - hddtemp
      - ipmitool
      - nvme-cli
    state: present
    update_cache: false
    enablerepo: "epel"
  register: install_hwtools_el7
  when: install_hwtools_el7 is undefined and ( (ansible_facts['distribution'] == 'CentOS') and (ansible_facts['distribution_major_version'] == '7') )
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - lm_sensors
      - dmidecode
      - pciutils
      - lshw
      - smartmontools
      - hddtemp
      - ipmitool
      - nvme-cli
    state: present
    update_cache: false
  register: install_hwtools_el9
  when: install_hwtools_el9 is undefined and ( (ansible_facts['distribution'] == 'AlmaLinux') or (ansible_facts['distribution'] == 'Fedora') )
  tags: packages

