---
- name: Bootstrap ansible python requirements
  ansible.builtin.raw: |-
    source /etc/os-release;
    [[ "${ID}" == "centos" && ${VERSION_ID:0:1} == "7" ]] && yum install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv;
    [[ "${ID}" == "almalinux" && ${VERSION_ID:0:1} == "9" ]] && { dnf install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv; /usr/bin/crb enable; }
    [[ "${ID}" == "fedora" ]] && dnf install -y python3 python3-devel python3-setuptools python3-pip python3-wheel python3-virtualenv;
    [[ "${ID}" == "ubuntu" ]] && apt install -y python3 python3-dev python3-setuptools python3-pip python3-wheel python3-virtualenv;
    exit 0;
  tags: packages
  register: python_install_result
  changed_when: false
