---
- name: Install epel and elrepo repositories
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - repo_epel_task.yml
    - repo_elrepo_task.yml
    - pkg_yum-utils_task.yml

- name: Install hardware management and monitoring tools - EL7
  ansible.builtin.yum:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - ipset
      - ipset-service
      - rsync
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: Install hardware management and monitoring tools - EL9
  ansible.builtin.dnf:
    name:
      - coreutils
      - util-linux
      - procps-ng
      - sysstat
      - cronie
      - crontabs
      - cronie-anacron
      - iproute
      - iproute-tc
      - ipset
      - ipset-service
      - rsync
    state: present
    update_cache: false
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Create /etc/ipset/ipset.d
  ansible.builtin.file:
    path: /etc/ipset/ipset.d
    state: directory
    mode: '0755'

- name: Install from pip the jc module
  ansible.builtin.pip:
    executable: pip3
    name:
      - jc
    extra_args: --user
    state: present

- name: Enable and start cron
  ansible.builtin.systemd:
    name: crond
    state: started
    enabled: true

- name: Set ipset to save on restart
  community.general.ini_file:
    path: /etc/sysconfig/ipset-config
    option: IPSET_SAVE_ON_STOP
    value: "yes"
    state: present
    no_extra_spaces: true
    modify_inactive_option: true

- name: Create /etc/ipset/ipset.d
  ansible.builtin.file:
    path: /etc/ipset/ipset.d
    state: directory
    mode: '0755'

- name: Set ipset to save on restart
  community.general.ini_file:
    path: /etc/sysconfig/ipset-config
    option: IPSET_DATA_DIR
    value: "/etc/ipset/ipset.d"
    state: present
    no_extra_spaces: true
    modify_inactive_option: true

- name: Enable and start ipset
  ansible.builtin.systemd:
    name: ipset
    state: started
    enabled: true

- name: User HOME/bin path
  ansible.builtin.copy:
    dest: /etc/profile.d/add_user_paths.sh
    content: |
        pathmunge $HOME/bin
        pathmunge $HOME/.local/bin
    mode: 0644
    owner: root
    group: root
    backup: false
    force: true

