---
- name: Add mdadm management scripts
  ansible.builtin.include_tasks: "{{ item }}"
  with_items:
    - mdraid_cli.yml

- name: Sync tools for system management
  ansible.builtin.copy:
    dest: /root/bin/
    src: "{{ playbook_dir }}/../additions/{{ item }}"
    owner: root
    group: root
    mode: '0700'
    force: true
  with_items:
    - broadcom_net/bnxtnvm
    - broadcom_sas/lsigetlinux.sh
    - broadcom_sas/sas2ircu
    - broadcom_sas/sas3flash
    - broadcom_sas/sas3ircu
    - broadcom_sas/storcli
    - broadcom_sas/storcliconf.ini

- name: Install from pip the jc module
  ansible.builtin.pip:
    executable: pip3
    name:
      - sasutils
    extra_args: --user
    state: latest

