---
- name: Sync ARECA cli executable
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/ARECA/arecacli"
    dest: /root/bin/
    owner: root
    group: root
    mode: "0700"
    force: true

- name: Sync info script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/ARECA/get_areca_info"
    dest: /root/bin/
    owner: root
    group: root
    mode: "0700"
    force: true

- name: Sync cron definition
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/ARECA/areca.cron"
    dest: /etc/cron.d/areca
    owner: root
    group: root
    mode: "0644"
    force: true
