---
- name: include pkg_mlsensor_task.yml
  ansible.builtin.include_tasks: pkg_mlsensor_task.yml

- name: Mlsensor config
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../additions/mlsensor/mlsensor.properties.j2"
    dest: /etc/mlsensor/mlsensor.properties
    owner: root
    group: root
    mode: '0644'
    force: true

- name: Restart mlsensor
  ansible.builtin.service:
    name: mlsensor
    state: restarted
    enabled: true

