---
- name: Fix /etc/slurm/conf.d/accounting.conf for slurm22
  ansible.builtin.lineinfile:
    path: /etc/slurm/conf.d/accounting.conf
    regexp: 'AccountingStoreJobComment=.*'
    line: "AccountingStoreFlags=job_comment"

- name: Start and enable munge
  ansible.builtin.systemd:
    name: munge
    state: restarted
    enabled: true

- name: Start and enable slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true

