---
- name: Include pkg_ipset_task.yml
  ansible.builtin.include_tasks: pkg_ipset_task.yml

## /etc/sysconfig/ipset-config
## IPSET_SAVE_ON_STOP="yes" !!!

- name: Mkdir /root/ipset_sync
  ansible.builtin.file:
    path: /root/ipset_sync
    state: directory
    mode: '0755'

- name: Copy ipset template definition
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/ipset/ipset_sets_def"
    dest: /root/ipset_sync/
    owner: root
    group: root
    mode: '0600'
    force: true

- name: Ipset rules
  ansible.builtin.template:
    src: "{{ playbook_dir }}/../additions/ipset/ipset.j2"
    dest: /root/ipset_sync/ipset.ansible
    owner: root
    group: root
    mode: '0600'
    force: true
  register: _ipset_rules_update
  vars:
    ipset_tables:
      - accept_ip:
      - accept_ip6:
      - accept_net:
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
      - accept_port_net6:
      - accept_port_tcp:
      - accept_port_udp:

- name: Ipset should be started
  ansible.builtin.systemd:
    name: ipset
    state: started
    enabled: true

- name: Create ipset sets
  ansible.builtin.command: "ipset -exist -file /root/ipset_sync/ipset_sets_def restore"
  changed_when: true

- name: Apply ipset content
  ansible.builtin.command: "ipset -exist -file /root/ipset_sync/ipset.ansible restore"
  changed_when: true

- name: Restart ipset
  ansible.builtin.systemd:
    name: ipset
    state: restarted
