---
- name: Install smartmontools - EL7
  ansible.builtin.yum:
    name:
      - smartmontools
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: Install smartmontools - EL9
  ansible.builtin.dnf:
    name:
      - smartmontools
    state: present
    update_cache: false
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Smartd config
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/smartctl/smartd.conf"
    dest: /etc/smartmontools/smartd.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true

- name: Smartd create customization path
  ansible.builtin.file:
    path: /etc/systemd/system/smartd.service.d/
    state: directory

- name: Smartd customize systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/smartd.service.d/override.conf
    content: |
        [Service]
        TimeoutStartSec=900
        Restart=on-failure
        RestartSec=30
    mode: 0644
    owner: root
    group: root
    backup: false
    force: true

- name: Smartd loggind directory
  ansible.builtin.file:
    path: /var/log/smartd/
    state: directory

- name: Smartd customize smartmontools default config
  ansible.builtin.copy:
    dest: /etc/sysconfig/smartmontools
    content: |
        smartd_opts="-q never -i 3600 -s /var/log/smartd/ -A /var/log/smartd/"
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true

- name: Update /usr/share/smartmontools/drivedb.h
  ansible.builtin.command: /usr/sbin/update-smart-drivedb -u github --trunk --no-verify

- name: Restart smartd
  ansible.builtin.systemd:
    name: smartd.service
    state: started
    daemon_reload: true
    enabled: true
