---
- name: Create systemd linger directory
  ansible.builtin.file:
    path: /var/lib/systemd/linger/
    state: directory

- name: Enable linger for this list of users
  ansible.builtin.copy:
    content: ""
    dest: "/var/lib/systemd/linger/{{ _linger_user }}"
    force: false
    group: root
    owner: root
    mode: 0644
  loop_control:
    loop_var: _linger_user
  loop: "{{ _linger_users_list }}"

