---
- name: Chrony configuration 85
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub85"
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - (ansible_facts['all_ipv4_addresses'] | ansible.utils.reduce_on_network('85.120.46.0/24') | length | int) > 0

- name: Chrony configuration 46
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub46"
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - (ansible_facts['all_ipv4_addresses'] | ansible.utils.reduce_on_network('46.243.114.128/25') | length | int) > 0

- name: Chrony configuration 10
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_priv10"
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - (ansible_facts['all_ipv4_addresses'] | ansible.utils.reduce_on_network('10.10.8.0/22') | length | int) > 0

- name: Chrony configuration 172
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_priv172"
    dest: /etc/chrony.conf
    mode: "0644"
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - (ansible_facts['all_ipv4_addresses'] | ansible.utils.reduce_on_network('172.20.0.0/24') | length | int) > 0

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true
  register: chrony_restarted

- name: Configure time system
  ansible.builtin.command: "{{ item }}"
  with_items:
    - /usr/bin/timedatectl set-local-rtc 0
    - /usr/bin/timedatectl set-timezone Europe/Bucharest
    - /usr/bin/timedatectl set-ntp 1
  when: chrony_restarted is succeeded
  changed_when: true
