---
- name: ipset should be started
  ansible.builtin.systemd:
    name: ipset
    state: started
    enabled: true

- name: Create ipset tables IPv4
  ansible.builtin.command: "{{ ipset_create_v4 }}"
  loop:
    - "ipset create accept_ip        hash:ip       family inet  hashsize 1024 maxelem 65536"
    - "ipset create accept_net       hash:net      family inet  hashsize 1024 maxelem 65536"
    - "ipset create accept_port_ip   hash:ip,port  family inet  hashsize 1024 maxelem 65536"
    - "ipset create accept_port_net  hash:net,port family inet  hashsize 1024 maxelem 65536"
    - "ipset create blacklist_ip     hash:ip       family inet  hashsize 1024 maxelem 65536"
    - "ipset create blacklist_net    hash:net      family inet  hashsize 1024 maxelem 65536"
    - "ipset create f2b-sshd         hash:ip       family inet  hashsize 1024 maxelem 65536 timeout 0"
  loop_control:
    loop_var: ipset_create_v4

- name: Create ipset tables IPv6
  ansible.builtin.command: "{{ ipset_create_v6 }}"
  loop:
    - "ipset create accept_ip6       hash:ip       family inet6 hashsize 1024 maxelem 65536"
    - "ipset create accept_net6      hash:net      family inet6 hashsize 1024 maxelem 65536"
    - "ipset create accept_port_ip6  hash:ip,port  family inet6 hashsize 1024 maxelem 65536"
    - "ipset create accept_port_net6 hash:net,port family inet6 hashsize 1024 maxelem 65536"
    - "ipset create blacklist_ip6    hash:ip       family inet6 hashsize 1024 maxelem 65536"
    - "ipset create blacklist_net6   hash:net      family inet6 hashsize 1024 maxelem 65536"
    - "ipset create f2b-sshd6        hash:ip       family inet6 hashsize 1024 maxelem 65536 timeout 0"
  loop_control:
    loop_var: ipset_create_v6

- name: restart ipset
  ansible.builtin.systemd:
    name: ipset
    state: restarted
