---
- name: Start and enable munge
  ansible.builtin.systemd:
    name: munge
    state: restarted
    enabled: true

- name: Start and enable slurmd
  ansible.builtin.systemd:
    name: slurmd
    state: restarted
    enabled: true
