---
- name: include pkg_gmond_task.yml
  ansible.builtin.include_tasks: pkg_gmond_task.yml

- name: Gmond customize systemd unit - create dir
  ansible.builtin.file:
    path: /etc/systemd/system/gmond.service.d/
    state: directory

- name: Gmond customize systemd unit
  ansible.builtin.copy:
    dest: /etc/systemd/system/gmond.service.d/
    src: "{{ playbook_dir }}/../additions/gmond_conf/gmond.service.d/override.conf"
    mode: 0644
    owner: root
    group: root
    backup: false
    force: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

