---
- name: Create systemd linger directory
  ansible.builtin.file:
    path: /var/lib/systemd/linger/
    state: directory

- name: Create systemd user@.service.d override directory
  ansible.builtin.file:
    path: /etc/systemd/system/user@.service.d/
    state: directory

- name: Enable linger for this list of users
  ansible.builtin.copy:
    content: ""
    dest: "/var/lib/systemd/linger/{{ _linger_user }}"
    force: false
    group: root
    owner: root
    mode: 0644
  loop_control:
    loop_var: _linger_user
  loop: "{{ _linger_users_list }}"

# https://github.com/systemd/systemd/issues/18293#issuecomment-1240300312
- name: Add to user@.service the delegation of cgroup modules
  ansible.builtin.copy:
    dest: "/etc/systemd/system/user@.service.d/delegate.conf"
    force: true
    group: root
    owner: root
    mode: 0644
    content: |
      [Service]
      Delegate=cpu cpuset io memory pids

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

