---
- name: Dump
  delegate_to: localhost
  run_once: true
  copy:
    content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
    dest: "/home/adrian/ansible/{{ inventory_hostname }}-dump.json"

