---
- include_tasks: yum-utils.yml

- name: Install elrepo repository
  yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: present
  tags: repo

- name: Enable elrepo
  command: yum-config-manager --enable elrepo-kernel elrepo-extras

- name: Install kernel-ml
  yum:
    name:
      - kernel-ml
      - kernel-ml-devel
    state: latest
    enablerepo: "elrepo,elrepo-kernel,elrepo-extras"
  tags: packages

