---
- name: Install packages on worker nodes
  ansible.builtin.yum:
    name: "{{ pkg_name }}"
    state: present
    update_cache: true
  loop_control:
    loop_var: pkg_name
  loop: "{{ package_list }}"
  tags: packages
