---
- name: Install packages
  ansible.builtin.yum:
    name: "{{ pkg_name }}"
    state: present
    update_cache: false
  loop_control:
    loop_var: pkg_name
  loop: "{{ package_list }}"
  tags: packages
