---
- name: Install chrony
  yum:
    name: chrony
    state: latest
  tags: packages

- name: Chrony configuration
  copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true

- name: timedatectl 1
  ansible.builtin.command: /usr/bin/timedatectl set-local-rtc 0
- name: timedatectl 2
  ansible.builtin.command: /usr/bin/timedatectl set-timezone Europe/Bucharest

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true

- name: timedatectl 3
  ansible.builtin.command: /usr/bin/timedatectl set-ntp 1

