---
- name: Include pkg_yum-utils_task.yml
  ansible.builtin.include_tasks: pkg_yum-utils_task.yml

- name: Install vobox requirements
  ansible.builtin.yum:
    name: [ 'HEP_OSlibs' ]
    state: present
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  tags: packages

- name: Install vobox packages
  ansible.builtin.yum:
    name: [ 'wlcg-vobox' ]
    state: present
    enablerepo: "wlcg,UMD-4-base,UMD-4-updates"
    exclude: "xrootd4-*"
  tags: packages

