---
- include_tasks: repo_epel_task.yml

- name: Install munge - EL7
  ansible.builtin.yum:
    name:
      - munge
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install munge - EL9
  ansible.builtin.dnf:
    name:
      - munge
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'

- name: Start and enable munge
  ansible.builtin.systemd:
    name: munge
    state: stopped
    enabled: true

