---
- name: Include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Install hardware monitoring tools on hardware machines (not vms) - Centos
  ansible.builtin.yum:
    name: [ 'rasdaemon.x86_64', 'edac-utils', 'linux-firmware', 'mdadm' ]
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install hardware monitoring tools on hardware machines (not vms) - Fedora
  ansible.builtin.dnf:
    name: [ 'rasdaemon.x86_64', 'edac-utils', 'linux-firmware', 'mdadm' ]
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'
