---
- include_tasks: repo_frontier_task.yml

- name: create squid dirs
  file:
    path: "{{ item }}"
    state: directory
    mode: 0644
  with_items:
    - /etc/squid
    - /home/frontier_logs/
    - /home/frontier_cache/

- name: Create squidconf
  copy:
    dest: "/etc/squid/squidconf"
    force: true
    mode: 0644
    content: |
      export FRONTIER_USER=frontier
      export FRONTIER_GROUP=frontier
      export SETSQUIDAFFINITY=true
      export SQUID_CLEAN_CACHE_ON_START=false

- name: Install Frontier packages
  yum:
    name: frontier-squid
    state: latest
    enablerepo: "cern-frontier"
  tags: packages

- name: frontier squid customizations
  copy:
    src: "{{ playbook_dir }}/../additions/frontier/customize.sh.vobox"
    dest: /etc/squid/customize.sh
    backup: true
    owner: frontier
    group: frontier
    mode: '0644'
    force: true

- name: proper ownership
  file:
    path: "{{ item }}"
    owner: frontier
    group: frontier
    state: directory
    recurse: true
  with_items:
    - /etc/squid
    - /home/frontier_logs/
    - /home/frontier_cache/

