---
- include_tasks: repo_cernvm_task.yml

- name: Install CVMFS packages
  yum:
    name: [ 'cvmfs', 'cvmfs-config-default' ]
    state: latest
    enablerepo: "cernvm,cernvm-config"
  tags: packages
