---
- ansible.builtin.import_tasks: repo_egi_igtf_task.yml

- name: Install certificates on newer distros EL9 or Fedora
  ansible.builtin.dnf:
    name:
      - ca-policy-egi-core
      - ca-policy-lcg
    state: latest
    enablerepo: "EGI-trustanchors"
  when: ansible_facts['distribution'] == 'AlmaLinux' or ansible_facts['distribution'] == 'Fedora'
  tags: packages
