---
- name: Include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Install HPC tools - EL9
  ansible.builtin.dnf:
    name:
      - lshw
      - hwloc
      - hwloc-devel
      - numactl
      - numad
      - numatop
    state: present
    update_cache: false
  when: ansible_facts['distribution'] == 'AlmaLinux' or ansible_facts['distribution'] == 'Fedora'
  tags: packages

- name: Install HPC tools - Fedora
  ansible.builtin.dnf:
    name:
      - lshw
      - hwloc
      - hwloc-plugins
      - hwloc-devel
      - numactl
      - numad
      - numatop
    state: present
    update_cache: false
  when: ansible_facts['distribution'] == 'Fedora'
  tags: packages

