---
- name: Install lm_sensors EL9
  ansible.builtin.dnf:
    name: lm_sensors
    state: present
  when: ( ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9' ) or ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages
