---
- include_tasks: repo_wlcg_task.yml

- name: Install vobox requirements - EL7
  ansible.builtin.yum:
    name: [ 'HEP_OSlibs' ]
    state: present
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: packages

- name: Install vobox requirements - EL9
  ansible.builtin.yum:
    name: [ 'HEP_OSlibs' ]
    state: present
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'
  tags: packages
