---
- ansible.builtin.import_tasks: repo_wlcg_task.yml

- name: lsc+vomses EL7
  ansible.builtin.yum:
    name:
      - wlcg-iam-lsc-ops
      - wlcg-iam-lsc-dteam
      - wlcg-iam-lsc-alice
      - wlcg-iam-vomses-alice
      - wlcg-iam-vomses-dteam
      - wlcg-voms-ops
      - wlcg-voms-dteam
      - wlcg-voms-alice
    state: latest
    enablerepo: "wlcg"
  when: ansible_facts['distribution'] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'
  tags: packages

- name: lsc+vomses EL9
  ansible.builtin.dnf:
    name:
      - wlcg-iam-lsc-ops
      - wlcg-iam-lsc-dteam
      - wlcg-iam-lsc-alice
      - wlcg-iam-vomses-alice
      - wlcg-iam-vomses-dteam
      - wlcg-voms-ops
      - wlcg-voms-dteam
      - wlcg-voms-alice
    state: latest
    enablerepo: "wlcg"
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ( ansible_facts['distribution_major_version'] | int  > 7 ) ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages
