---
- name: Install chrony EL7
  ansible.builtin.yum:
    name: chrony
    state: present
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: packages

- name: Install chrony EL9
  ansible.builtin.yum:
    name: chrony
    state: present
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9' ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages

# - debug:
#     msg: |
#       ansible_all_ipv4_addresses: {{ ansible_all_ipv4_addresses }}
#       _network_reduced: "{{ ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') }}"
#       _result_lenght: "{{ ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') | length }}"
#       _result_value: "{{ ( ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') | length | int ) > 0 }}"

- name: Chrony configuration 85
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub85"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - (  ansible_all_ipv4_addresses | ansible.utils.reduce_on_network( '85.120.46.0/24' ) | length | int ) > 0

- name: Chrony configuration 46
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub46"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - ( ansible_all_ipv4_addresses | ansible.utils.reduce_on_network( '46.243.114.128/25' ) | length | int ) > 0

- name: Chrony configuration 10
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub10"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - ( ansible_all_ipv4_addresses | ansible.utils.reduce_on_network( '10.10.8.0/22' ) | length | int ) > 0

- name: Chrony configuration 172
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub10"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured is skipped
    - ( ansible_all_ipv4_addresses | ansible.utils.reduce_on_network( '172.20.0.0/24' ) | length | int ) > 0

