---
- include_tasks: pkg_yum-utils_task.yml

- name: Install vobox requirements
  ansible.builtin.yum:
    name: [ 'HEP_OSlibs', 'wlcg-voms-alice', 'wlcg-voms-dteam', 'wlcg-voms-ops' ]
    state: latest
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  tags: packages

- name: Install vobox packages
  ansible.builtin.yum:
    name: [ 'wlcg-vobox' ]
    state: latest
    enablerepo: "wlcg,UMD-4-base,UMD-4-updates"
    exclude: "xrootd4-*"
  tags: packages

