---
- name: Include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Include repo_wlcg_task.yml
  ansible.builtin.include_tasks: repo_wlcg_task.yml

- name: Install EGI package requirements - EL9
  ansible.builtin.dnf:
    name: [ 'HEP_OSlibs', 'tcsh.x86_64', 'fetch-crl.noarch' ]
    state: present
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'
  tags: packages
