---
- include_tasks: repo_epel_task.yml

- name: Install hardware monitoring tools on hardware machines (not vms) - Centos
  ansible.builtin.yum:
    name: [ 'tuned', 'tuned-utils', 'tuna' ]
    state: latest
    update_cache: true
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

- name: Install hardware monitoring tools on hardware machines (not vms) - Fedora
  ansible.builtin.dnf:
    name: [ 'tuned', 'tuned-utils', 'tuna' ]
    state: latest
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'

