---
- include_tasks: pkg_cvmfs.yml

- name: create cvmfs cache
  file: path="{{ cvmfs_cache_base }}" state=directory group=cvmfs owner=cvmfs mode='0700'

- name: create cvmfs cache
  file: path="{{ cvmfs_cache_base }}/.." state=directory group=cvmfs owner=cvmfs mode='0700'

- name: Set cvmfs cache
  blockinfile:
    path: /etc/cvmfs/default.local
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
    marker_begin: "CVMFS CACHE BEGIN"
    marker_end: "CVMFS CACHE END"
    block: "CVMFS_CACHE_BASE='{{ cvmfs_cache_base }}'"

