---
- name: Install yum utils EL7
  ansible.builtin.yum:
    name: ['yum-utils', 'yum-plugin-fastestmirror', 'yum-plugin-priorities', 'yum-plugin-protectbase']
    state: present
    update_cache: false
  register: yum_utils_install_el7
  when: yum_utils_install_el7 is undefined and ( ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7' )

- name: Yum prefer IPv4 - EL7
  community.general.ini_file:
    path: /etc/yum.conf
    section: main
    option: ip_resolve
    value: 4
    no_extra_spaces: true
  register: yum_prefer_ipv4_el7
  when: yum_prefer_ipv4_el7 is undefined and ( ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7' )

- name: Install yum utils EL9/Fedora
  ansible.builtin.dnf:
    name: ['yum', 'dnf-utils', 'dnf-plugins-core']
    state: present
    update_cache: false
  register: yum_utils_install_el9
  when: yum_utils_install_el9 is undefined and ( ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora' )

- name: Dnf prefer IPv4 - EL9
  ansible.builtin.command: /usr/bin/dnf config-manager --save --setopt=install_weak_deps=False --setopt=ip_resolve=4
  register: dnf_prefer_ipv4_el9
  when: dnf_prefer_ipv4_el9 is undefined and ( ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora' )

- name: Task name
  ansible.builtin.stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_testing_present

- name: Task name
  ansible.builtin.stat:
    path: /etc/yum.repos.d/epel-testing.repo
  register: epel_testing_present

- name: Epel - exclude nordugrid
  community.general.ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: exclude
    value: *nordugrid-*
    create: false
    no_extra_spaces: true
  when: epel_testing_present.stat.exists

- name: Epel-testing - exclude nordugrid
  community.general.ini_file:
    path: /etc/yum.repos.d/epel-testing.repo
    section: epel-testing
    option: exclude
    value: *nordugrid-*
    create: false
    no_extra_spaces: true
  when: epel_testing_present.stat.exists

