---
- name: Install Java openjdk 11
  ansible.builtin.yum:
    name: [ 'java-11-openjdk.x86_64', 'java-11-openjdk-headless.x86_64', 'icedtea-web.x86_64' ]
    state: latest
    update_cache: true
  when: ansible_facts[ 'os_family' ] == 'RedHat'

