---
- name: Include pkg_phpremi_task.yml
  ansible.builtin.include_tasks: pkg_phpremi_task.yml

- name: Installing DOLIBARR php packages (latest)
  ansible.builtin.dnf:
    name:
      - 


    state: present