---
- name: Include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Install tuned - EL7
  ansible.builtin.yum:
    name: ['fail2ban-selinux', 'fail2ban-server', 'fail2ban-systemd']
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts['distribution_major_version'] == '7'

- name: Install tuned - EL9
  ansible.builtin.dnf:
    name: ['fail2ban-selinux', 'fail2ban-server', 'fail2ban-systemd']
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Install tuned - Fedora
  ansible.builtin.dnf:
    name: ['fail2ban-selinux', 'fail2ban-server', 'fail2ban-systemd']
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'Fedora'
