---
- include_tasks: repo_epel_task.yml

- include_tasks: pkg_munge_task.yml

- name: Install slurmd - EL7
  ansible.builtin.yum:
    name:
      - slurm-slurmd
      - slurm-contribs
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install slurmd - EL9
  ansible.builtin.dnf:
    name:
      - slurm-slurmd
      - slurm-contribs
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'

- name: Start and enable slurmd
  ansible.builtin.systemd:
    name: slurmd
    enabled: true
