---
- include_tasks: repo_epel_task.yml

- name: Install hardware monitoring tools on hardware machines (not vms) - Centos
  ansible.builtin.yum:
    name: [ 'edac-utils', 'linux-firmware', 'lldpd', 'mdadm' ]
    state: latest
    update_cache: true
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install hardware monitoring tools on hardware machines (not vms) - Fedora
  ansible.builtin.dnf:
    name: [ 'edac-utils', 'linux-firmware', 'lldpd', 'mdadm' ]
    state: latest
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'Fedora'

