---
- name: Install lldpd EL7
  ansible.builtin.yum:
    name: lldpd
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install lldpd EL9
  ansible.builtin.dnf:
    name: lldpd
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Install lldpd Fedora
  ansible.builtin.dnf:
    name: lldpd
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'Fedora'

