---
- include_tasks: pkg_yum-utils_task.yml

- name: Install DPM head requirements
  ansible.builtin.yum:
    name: [ 'dmlite-dpmdisk-domeonly', 'dmlite-dpm-xrootd', 'vomsxrd' ]
    state: latest
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  tags: packages

- name: Enable and start
  ansible.builtin.systemd:
    name: fetch-crl-cron
    state: restarted
    enabled: true

