---
- name: Install ganglia-gmond - EL9
  ansible.builtin.dnf:
    name: [ 'ganglia', 'ganglia-gmond' ]
    state: present
    update_cache: false
  when: ( ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9' ) or ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages

