---
- include_tasks: repo_elrepo_task.yml

- name: Install kernel-ml
  ansible.builtin.yum:
    name: [ 'kernel-ml', 'kernel-ml-devel' ]
    state: latest
    enablerepo: "elrepo,elrepo-kernel,elrepo-extras"
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: packages

- name: Set grub default to 0
  ansible.builtin.lineinfile: path="/etc/default/grub" regexp='GRUB_DEFAULT="(.*)"' line='GRUB_DEFAULT=0'

- name: Re-create grub conf
  ansible.builtin.command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg

