---
- include_tasks: repo_egi_igtf_task.yml

- name: Install CVMFS packages
  yum:
    name: [ 'ca-policy-egi-core', 'ca-policy-lcg.noarch' ]
    state: latest
    enablerepo: "EGI-trustanchors"
  tags: packages

