---
- ansible.builtin.import_tasks: repo_influxdata_task.yml

- name: Install influxdb2 EL9
  ansible.builtin.dnf:
    name:
      - influxdb2
    state: present
    enablerepo: "influxdata"
  when: ( ansible_facts['distribution'] == 'AlmaLinux' and ( ansible_facts['distribution_major_version'] | int  > 7 ) ) or ansible_facts['distribution'] == 'Fedora'
  tags: packages
