---
- name: Install apptainer EL7
  ansible.builtin.yum:
    name: [ 'apptainer', 'apptainer-suid' ]
    state: present
    enablerepo: "{{ 'Rocks-7.0' if rocks_node is defined else 'epel' }}"
    disablerepo: "UMD*"
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: packages

- name: Install apptainer EL9
  ansible.builtin.dnf:
    name: [ 'apptainer', 'apptainer-suid' ]
    state: present
    enablerepo: "epel"
    disablerepo: "UMD*"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9'
  tags: packages

- name: Install apptainer Fedora
  ansible.builtin.dnf:
    name: [ 'apptainer', 'apptainer-suid' ]
    state: present
  when: ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages
