---
- name: include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Install munge - EL9
  ansible.builtin.dnf:
    name:
      - munge
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' or ansible_facts[ 'distribution' ] == 'Fedora'
  tags: packages

