---
- name: Include pkg_yum-utils_task.yml
  ansible.builtin.include_tasks: pkg_yum-utils_task.yml

- name: Include pkg_hep_oslibs_task.yml
  ansible.builtin.include_tasks: pkg_hep_oslibs_task.yml

- name: Install vobox packages
  ansible.builtin.dnf:
    name: [ 'wlcg-vobox' ]
    state: present
    enablerepo: "wlcg,UMD-5-release,UMD-5-contrib"
    exclude: "xrootd4-*"
  tags: packages

