---
- name: Install chrony
  ansible.builtin.yum:
    name: chrony
    state: latest
  tags: packages

- debug:
    msg: |
      ansible_all_ipv4_addresses: {{ ansible_all_ipv4_addresses }}
      _network_reduced: "{{ ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') }}"
      _result_lenght: "{{ ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') | length }}"
      _result_value: "{{ ( ansible_all_ipv4_addresses | ansible.utils.reduce_on_network('85.120.46.0/24') | length | int ) > 0 }}"

- name: Chrony configuration 85
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub85"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - ( ( ansible_facts['ansible_all_ipv4_addresses'] | ansible.utils.reduce_on_network( '85.120.46.0/24' ) | length | int ) > 0 )

- name: Chrony configuration 46
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub46"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured.skipped
    - ( ansible_facts['ansible_all_ipv4_addresses'] | ansible.utils.reduce_on_network( '46.243.114.128/25' ) | length | int ) > 0

- name: Chrony configuration 10
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub10"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured.skipped
    - ( ansible_facts['ansible_all_ipv4_addresses'] | ansible.utils.reduce_on_network( '10.10.8.0/22' ) | length | int ) > 0

- name: Chrony configuration 172
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/chrony/chrony.conf.client_pub10"
    dest: /etc/chrony.conf
    mode: 0644
    owner: root
    group: root
    backup: true
    force: true
  register: chrony_is_configured
  when:
    - chrony_is_configured.skipped
    - ( ansible_facts['ansible_all_ipv4_addresses'] | ansible.utils.reduce_on_network( '172.20.0.0/24' ) | length | int ) > 0

- name: timedatectl 1
  ansible.builtin.command: /usr/bin/timedatectl set-local-rtc 0

- name: timedatectl 2
  ansible.builtin.command: /usr/bin/timedatectl set-timezone Europe/Bucharest

- name: Enable and start chronyd
  ansible.builtin.systemd:
    name: chronyd
    state: restarted
    enabled: true

- name: timedatectl 3
  ansible.builtin.command: /usr/bin/timedatectl set-ntp 1

