---
- include_tasks: repo_cernvm_task.yml

- name: Install CVMFS packages
  yum:
    name: [ 'cvmfs', 'cvmfs-config-default' ]
    state: latest
    enablerepo: "cernvm,cernvm-config"
  tags: packages

- name: add cvmfs.default
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/cvmfs/default.local.base"
    dest: /etc/cvmfs/default.local
    owner: root
    group: root
    mode: '0644'
    force: yes

