---
- name: Install hardware monitoring tools on hardware machines (not vms) - Centos
  ansible.builtin.yum:
    name: [ 'numad', 'numactl', 'tuned', 'tuned-utils', 'powertop' ]
    state: latest
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install hardware monitoring tools on hardware machines (not vms) - Fedora
  ansible.builtin.dnf:
    name: [ 'numad', 'numactl', 'tuned', 'tuned-utils', 'powertop' ]
    state: latest
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'Fedora'

