---
- name: include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Install tuned - EL9
  ansible.builtin.dnf:
    name: [ 'tuned', 'tuned-utils', 'tuna' ]
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Install tuned - Fedora
  ansible.builtin.dnf:
    name: [ 'tuned', 'tuned-utils', 'tuna' ]
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'Fedora'
