---
- include_tasks: pkg_yum-utils_task.yml

- name: Install DPM head requirements
  ansible.builtin.yum:
    name: [ 'dmlite-dpmhead-domeonly', 'dmlite-dpm-xrootd', 'vomsxrd', 'mariadb', 'mariadb-server'  ]
    state: latest
    enablerepo: "epel,wlcg"
    disablerepo: "UMD*"
  tags: packages

- name: Enable and start fetch-crl
  ansible.builtin.systemd:
    name: fetch-crl-cron
    state: restarted
    enabled: true

- name: Enable and start mariadb
  ansible.builtin.systemd:
    name: mariadb
    state: started
    enabled: true

