---
- include_tasks: repo_cernvm_task.yml

- name: Install autofs
  ansible.builtin.yum:
    name: [ 'autofs' ]
    state: latest

- name: Install CVMFS packages
  ansible.builtin.yum:
    name: [ 'cvmfs', 'cvmfs-config-default' ]
    state: latest
    enablerepo: "cernvm,cernvm-config"
    disablerepo: "UMD*"
  tags: packages

- name: Configure cvmfs autofs
  ansible.builtin.command: /usr/bin/cvmfs_config setup

- name: Enable and restart autofs
  ansible.builtin.systemd:
    name: autofs.service
    state: restarted
    enabled: true

- name: add cvmfs.default
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/cvmfs/default.local.base"
    dest: /etc/cvmfs/default.local
    owner: root
    group: root
    mode: '0644'
    force: true

