---
- name: Enable ElRepo Repository on EL 9
  ansible.builtin.dnf:
    name: elrepo-release.noarch
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'
  tags: repo

- name: Enable permanently elrepo
  community.general.ini_file:
    path: /etc/yum.repos.d/elrepo.repo
    section: elrepo
    option: enabled
    value: '1'
    mode: '0644'
    create: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Enable permanently elrepo-kernel
  community.general.ini_file:
    path: /etc/yum.repos.d/elrepo.repo
    section: elrepo-kernel
    option: enabled
    value: '1'
    mode: '0644'
    create: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Enable permanently elrepo-extras
  community.general.ini_file:
    path: /etc/yum.repos.d/elrepo.repo
    section: elrepo-extras
    option: enabled
    value: '1'
    mode: '0644'
    create: false
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

