---
- name: Include pkg_yum-utils_task.yml
  ansible.builtin.include_tasks: pkg_yum-utils_task.yml

- name: Include repo_epel_task.yml
  ansible.builtin.include_tasks: repo_epel_task.yml

- name: Remi key import - EL9
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi
    state: present
  when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'
  tags: repo

- name: Install remi repository EL9
  ansible.builtin.dnf:
    name:
      - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: present
  when: ansible_facts['distribution'] == 'AlmaLinux' and ansible_facts['distribution_major_version'] == '9'
  tags: repo

- name: Remi key import - Fedora
  ansible.builtin.rpm_key:
    key: https://rpms.remirepo.net/fedora/{{ ansible_facts["distribution_major_version"] }}/RPM-GPG-KEY-remi
    state: present
  when: ansible_facts['distribution'] == 'Fedora'
  tags: repo

- name: Install rpmfusion repository Fedora
  ansible.builtin.dnf:
    name:
      - https://rpms.remirepo.net/fedora/remi-release-{{ ansible_facts["distribution_major_version"] }}.rpm
    state: present
  when: ansible_facts['distribution'] == 'Fedora'
  tags: repo
