---
- name: EGI IGTF repo install
  ansible.builtin.yum_repository:
    name: EGI-trustanchors
    description: EGI-trustanchors
    file: EGI-trustanchors
    baseurl: http://repository.egi.eu/sw/production/cas/1/current/
    gpgkey: http://repository.egi.eu/sw/production/cas/1/GPG-KEY-EUGridPMA-RPM-3
    gpgcheck: true
    enabled: true
    state: present
    owner: root
    group: root
    mode: 0644
  tags: repo
