---
- include_tasks: pkg_yum-utils_task.yml

- name: Enable ElRepo Repository on CentOS 7
  ansible.builtin.yum:
    name: elrepo-release.noarch
    state: present
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: repo

- name: Enable ElRepo Repository on EL 9
  ansible.builtin.dnf:
    name: elrepo-release.noarch
    state: present
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9'
  tags: repo

