---
- name: Import Nordugrid key
  ansible.builtin.rpm_key:
    state: present
    key: http://download.nordugrid.org/RPM-GPG-KEY-nordugrid-6

- name: Install Nordugrid repository EL7
  ansible.builtin.yum:
    name: https://download.nordugrid.org/packages/nordugrid-release/releases/6.1/centos/el7/x86_64/nordugrid-release-6.1-1.el7.noarch.rpm
    state: present
  when: ansible_facts[ 'distribution' ] == 'CentOS' and ansible_facts[ 'distribution_major_version' ] == '7'
  tags: repo

- name: Install Nordugrid repository EL9
  ansible.builtin.dnf:
    name: https://download.nordugrid.org/packages/nordugrid-release/releases/6.1/rocky/9/x86_64/nordugrid-release-6.1-1.el9.noarch.rpm
    state: present
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux' and ansible_facts[ 'distribution_major_version' ] == '9'
  tags: repo

- name: Install Nordugrid repository Fedora
  ansible.builtin.dnf:
    name: https://download.nordugrid.org/packages/nordugrid-release/releases/6.1/fedora/38/x86_64/nordugrid-release-6.1-1.fc38.noarch.rpm
    state: present
  when: ansible_facts[ 'distribution' ] == 'Fedora'
  tags: repo

- name: Check existence of epel.repo
  ansible.builtin.stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_present

- name: Check existence of epel-testing.repo
  ansible.builtin.stat:
    path: /etc/yum.repos.d/epel-testing.repo
  register: epel_testing_present

- name: Epel - exclude nordugrid
  community.general.ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: exclude
    value: "*nordugrid-*"
    create: false
    no_extra_spaces: true
  when: epel_present.stat.exists

- name: Epel-testing - exclude nordugrid
  community.general.ini_file:
    path: /etc/yum.repos.d/epel-testing.repo
    section: epel-testing
    option: exclude
    value: "*nordugrid-*"
    create: false
    no_extra_spaces: true
  when: epel_testing_present.stat.exists
