---
- include_tasks: yum-utils_task.yml

- name: Enable EPEL Repository on CentOS 8
  dnf:
    name: https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: latest
    update_cache: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '8'
  tags: repo

- name: Enable EPEL Repository on CentOS 7
  yum:
    name: https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
    state: latest
    update_cache: True
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
  tags: repo

