---
- name: UMD key import
  command: rpm --import http://repository.egi.eu/sw/production/umd/UMD-RPM-PGP-KEY
  args:
    warn: no

- name: UMD4 repo on EL7
  yum:
    name: http://repository.egi.eu/sw/production/umd/5/centos7/x86_64/base/umd-release-5.0.0-1.el7.centos.noarch.rpm
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

