---
- name: Negativo epel-nvidia
  ansible.builtin.yum_repository:
    name: epel-nvidia
    description: negativo17 - Nvidia
    file: /etc/yum.repos.d/epel-nvidia.repo
    baseurl: https://negativo17.org/repos/nvidia/epel-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: true
    enabled: true
    metadata_expire: 21600
    skip_if_unavailable: true
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['ansible_distribution'] == 'AlmaLinux'
  tags: repo

- name: Negativo fedora-nvidia
  ansible.builtin.yum_repository:
    name: fedora-nvidia
    description: negativo17 - Nvidia
    file: /etc/yum.repos.d/fedora-nvidia.repo
    baseurl: https://negativo17.org/repos/nvidia/fedora-$releasever/$basearch/
    gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
    gpgcheck: true
    enabled: true
    metadata_expire: 21600
    skip_if_unavailable: true
    state: present
    owner: root
    group: root
    mode: 0644
  when: ansible_facts['ansible_distribution'] == 'Fedora'
  tags: repo

