---
- include_tasks: yum-utils.yml

- name: Install Frontier repository EL7
  yum:
    name: http://frontier.cern.ch/dist/rpms/RPMS/noarch/frontier-release-1.1-1.noarch.rpm
    state: present
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'
  tags: repo

