---
- name: Install lldpd EL7
  yum:
    name: lldpd
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install lldpd EL9
  dnf:
    name: lldpd
    state: present
    update_cache: false
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Install lldpd Fedora
  dnf:
    name: lldpd
    state: present
    update_cache: false
  when: ansible_facts[ 'distribution' ] == 'Fedora'

- name: Ansible create file with content example
  copy:
    dest: "/etc/lldpd.d/lldpd.conf"
    mode: 0644
    owner: root
    group: root
    content: |
      configure lldp portidsubtype ifname
      update

- name: Restart lldpd
  service:
    name: lldpd
    state: restarted
    enabled: true

