---
- name: Install lldpd EL
  yum:
    name: lldpd
    state: latest
    update_cache: true
    enablerepo: "epel"
  when: ansible_facts[ 'distribution' ] == 'CentOS'

- name: Install lldpd Fedora
  dnf:
    name: lldpd
    state: latest
    update_cache: true
  when: ansible_facts[ 'distribution' ] == 'Fedora' or ansible_facts[ 'distribution' ] == 'AlmaLinux'

- name: Ansible create file with content example
  copy:
    dest: "/etc/lldpd.d/lldpd.conf"
    mode: 0644
    owner: root
    group: root
    content: |
      configure lldp portidsubtype ifname
      update

- name: Restart lldpd
  service:
    name: lldpd
    state: restarted
    enabled: true

