---
- name: Disable un-needed timers
  ansible.builtin.systemd_service:
    name: "{{ _timer_disable }}"
    state: stopped
    enabled: false
  loop_control:
    loop_var: _timer_disable
  loop:
    - "dnf-makecache.timer"
    - "mlocate-updatedb.timer"
  ignore_errors: true

- name: Create system directories
  ansible.builtin.file:
    path: "{{ sys_dir }}"
    state: directory
    mode: '1777'
  loop_control:
    loop_var: sys_dir
  loop:
    - /data/home
    - /data/arcce
    - /data/workdir
    - /data/scratch

- name: Create symlink - workdir
  ansible.builtin.file:
    src: /data/workdir
    dest: /workdir
    state: link

- name: Create symlink - scratch
  ansible.builtin.file:
    src: /data/scratch
    dest: /scratch
    state: link

