---
- name: Create ALICE work dirs
  ansible.builtin.file:
    path: "{{ alice_dir }}"
    state: directory
    recurse: true
    owner: aliprod
    group: aliprod
  loop_control:
    loop_var: alice_dir
  loop:
    - /data/ALICE
    - /data/ALICE/cache
    - /data/ALICE/alien-logs
    - /data/ALICE/tmp

- name: set limits for aliprod user
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../additions/limits.d/99-aliprod_limits.conf"
    dest: /etc/security/limits.d/
    owner: root
    group: root
    mode: '0644'
    force: true

