#!/usr/bin/env bash

NAME="1"

# list of devices
###   DEFINE THE LIST OF DEVICES !!!
# raid_comp="/dev/sda /dev/sdm /dev/sdn /dev/sdd /dev/sdc /dev/sdb /dev/sdf /dev/sde /dev/sdg /dev/sdh /dev/sdi /dev/sdj"

[[ -z "${raid_comp}" ]] && { echo "raid components not defined"; exit 1; }

MD_NAME="md${NAME}"
RAID_NAME="data${NAME}"

# get how many devices
raid_comp_arr=(${raid_comp})
raid_devices=${#raid_comp_arr[@]}

# customize devices to be partitions
MDADM_PART_LIST=""
for disk in ${raid_comp}; do
    [[ -z "${MDADM_PART_LIST}" ]] && MDADM_PART_LIST="${disk}1" || MDADM_PART_LIST="${MDADM_PART_LIST} ${disk}1"
done

# create partition tables and define an ext4 partion on each device
for disk in ${raid_comp}; do
    bash ./format_md_component "${disk}" "${MD_NAME}"
done

# create mdadm raid
mdadm --create --raid-devices="${raid_devices}" --metadata=1.2 --chunk=32K --level=raid6 --homehost=any --name=${RAID_NAME} "/dev/${MD_NAME}" ${MDADM_PART_LIST}

