#!/usr/bin/env bash

DISK="${1}"
MD="${2}"
DISK="$(echo ${1} | sed 's#/dev/##' )"

help () {
echo "${0} DISK_DEV MD_DEV
MD_DEV: MD_DEV of which the partition will be part of
"
}

[[ -z "${DISK}" ]] && { echo "1st arg (dev disk) missing"; help; exit 1; }
[[ -z "${MD}" ]] && { echo "2nd arg (md device name) missing;"; help; exit 1; }

echo "Preparing /dev/${DISK}"
mdadm --zero-superblock "/dev/${DISK}1" 2>/dev/null
sgdisk --zap-all "/dev/${DISK}"
partprobe "/dev/${DISK}"
sgdisk --clear --mbrtogpt "/dev/${DISK}"
sgdisk --set-alignment "/dev/${DISK}"
sgdisk --new=0:0:0 "/dev/${DISK}"
sgdisk --change-name=1:"${MD}" "/dev/${DISK}"
sgdisk --print "/dev/${DISK}"
echo


