#!/usr/bin/env bash

DISK="${1}"
MD="${2}"
DISK="$(echo ${1} | sed 's#/dev/##' )"

help () {
echo "${0} DISK_DEV MD_DEV
MD_DEV: MD_DEV of which the partition will be part of
"
}

[[ -z "${DISK}" ]] && { echo "1st arg (dev disk) missing"; help; exit 1; }
[[ -z "${MD}" ]] && { echo "2nd arg (md device name) missing;"; help; exit 1; }

parted -s -a optimal "/dev/${DISK}" mklabel gpt
parted -s -a optimal "/dev/${DISK}" mkpart "${MD}" 0% 100%
mdadm --zero-superblock "/dev/${DISK}1" 2>/dev/null
parted "/dev/${DISK}" print free

