#!/usr/bin/env bash

DISK="${1}"
MD="${2}"
DISK="$(echo ${1} | sed 's#/dev/##' )"

[[ -z "${DISK}" ]] && { echo "1st arg (dev disk) missing"; exit 1; }
[[ -z "${MD}" ]] && { echo "3nd arg (index of md device) missing; it will be the name of the gpt partition"; exit 1; }

parted -s -a optimal "/dev/${DISK}" mklabel gpt
parted -s -a optimal "/dev/${DISK}" mkpart "md${MD}" 0% 100%
mdadm --zero-superblock "/dev/${DISK}1" 2>/dev/null
parted "/dev/${DISK}" print free

