#!/usr/bin/env bash

MD="${1}"
shift

[[ -z "${MD}" ]] && { echo "1st arg should be the md dev name"; exit 1; }

md_devs="$(/usr/bin/find /sys/devices/virtual/block -iwholename "*/md" -exec /usr/bin/dirname '{}' \;)"
readarray -t md_list <<< "$(for d in ${md_devs}; do /usr/bin/basename ${d}; done)"
[[ ! "${md_list[@]}" =~ "${MD}" ]] && { echo "md dev >${MD}< not found in the list of local md devices: ${md_list[@]}"; exit 1; }

ACTION="${1}"
shift

help () {
echo "${0} check | repair| idle | status"
}

case "${ACTION}" in
  resync)
  echo resync > "/sys/block/${MD}/md/sync_action"
  ;;
  recover)
  echo recover > "/sys/block/${MD}/md/sync_action"
  ;;
  check)
  echo check > "/sys/block/${MD}/md/sync_action"
  ;;
  repair)
  echo repair > "/sys/block/${MD}/md/sync_action"
  ;;
  idle)
  echo idle > "/sys/block/${MD}/md/sync_action"
  ;;
  status)
  echo "${MD} state: $(< /sys/devices/virtual/block/${MD}/md/array_state) ; Progress : $(< /sys/devices/virtual/block/${MD}/md/sync_completed)"
  echo "${MD} Error count (nr of sectors (in pages)): $(< /sys/devices/virtual/block/${MD}/md/mismatch_cnt)"
  ;;
  *) # unsupported flags, just catch any mistakes
  help
  ;;
esac

