#!/bin/bash

DISK=${1}
MD=${2}
DISK="$(echo ${1} | sed 's#/dev/##' )"

[[ -z "${DISK}" ]] && { echo "argument empty, specify disk"; exit 1;}

parted -s -a optimal /dev/"${DISK}" mklabel gpt
parted -s -a optimal /dev/"${DISK}" mkpart ${MD} 0% 100%
mdadm --zero-superblock /dev/"${DISK}1"
parted /dev/"${DISK}" print

