---
- hosts: "{{ target | default('wn_alien') }}"
  gather_facts: False
  vars:
    _linger_users_list:
      - aliprod

    cvmfs_cache_size: "51200"
    cvmfs_cache_base: "/data/cvmfs/cache"
    cvmfs_repos: "cvmfs-config.cern.ch,alice.cern.ch,alice-ocdb.cern.ch"
    cvmfs_proxy_list: "http://alien.spacescience.ro:3128;http://issaf.spacescience.ro:3128;http://monitor.spacescience.ro:3128"

    chrony_base_ip: "pub85"

    mounts_list:
      - "{{ playbook_dir }}/../additions/mounts_alien/var-arc-sessions.mount"
      - "{{ playbook_dir }}/../additions/mounts_alien/var-arc-sessions.automount"
    mounts_list_enable:
      - "var-arc-sessions.automount"

    host_src_data_sync: "alien.spacescience.ro"

    iptables_v4_custom_table_setup: ""
    iptables_v6_custom_table_setup: ""
    ip_v4_filter_custom_rule_after_ipsets: ""
    ip_v6_filter_custom_rule_after_ipsets: ""

    ipset_tables:
      - accept_ip:
        - "85.120.46.17"
        - "172.18.0.1"
      - accept_ip6:
        - "2001:b30:4210:1::17"
      - accept_net:
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
        - "172.18.0.0/22,22"
      - accept_port_net6:

    profile: iss

    sysctl_list:
      - "{{ playbook_dir }}/../additions/sysctl.d/60-memory.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/70-mtu.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/72-packet_tuning.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv4.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv6.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-netcore.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-fs.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-kernel.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-raid_speed.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-delayacct.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-inotify.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-security.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/80-network_buffers_25GB.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-singularity.conf"

    tuning_list:
      - "{{ playbook_dir }}/../additions/root_tuning.d/00-blockdev.tune"
      - "{{ playbook_dir }}/../additions/root_tuning.d/00-nm_mtu.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/01-mtu_txq.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/05-fq_shape.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/20-ring.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/25-channels.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/10-nic_lldp_off.tune_eth"

  vars_files:
      - "{{ playbook_dir }}/../additions/users_alien/user_group_info_wn.yml"
      - "{{ playbook_dir }}/../additions/users_alien/delete_users_groups.yml"
      - "{{ playbook_dir }}/../additions/data_sync_alien/data_list.yml"
      - "{{ playbook_dir }}/../additions/data_sync_alien/data_list_exclusive.yml"
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_alien_wn.yml"

  # Let's not do it dynamically - we are not on frontend
  # pre_tasks:
  # - name: Create user yml list
  #   local_action: command cmd="{{ playbook_dir }}/../additions/users/make_id_lists"
  # run_once: True

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/pkg_igtfca_task.yml"
      - "tasks/pkg_lsc_vomses_task.yml"
      - "tasks/pkg_hpc_task.yml"
      - "tasks/pkg_munge_task.yml"
      - "tasks/pkg_arcce_task.yml"
      - "tasks/pkg_hep_oslibs_task.yml"
      - "tasks/pkg_apptainer_task.yml"
      - "tasks/pkg_nhc_task.yml"
      - "tasks/pkg_slurm_task.yml"
      - "tasks/cfg_firewall_task.yml"
      - "tasks/cfg_cvmfs_task.yml"
      - "tasks/cfg_chrony_task.yml"
      - "tasks/cfg_ssh_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/cfg_smartd_task.yml"
      - "tasks/cfg_lldpd_task.yml"
      - "tasks/cfg_tuned_task.yml"
      - "tasks/cfg_tuning_infra.yml"
      - "tasks/cfg_gmond_alien.yml"
      - "tasks/cfg_slurm22_task.yml"
      - "tasks/tune_sysctl_task.yml"
      - "tasks/tune_scripts_task.yml"
      - "tasks/pkg_utils_task.yml"
###      - "tasks/sync_data_task.yml"
      - "tasks/mounts_task.yml"
      - "tasks/alice_wn_prepare_task.yml"
      - "tasks/users_home_task.yml"
      - "tasks/alice_wn_prepare_aliprod_task.yml"
      - "tasks/cfg_linger4user_task.yml"


