- hosts: "{{ target | default('sbdii.spacescience.ro') }}"
  gather_facts: False
  vars:
    chrony_base_ip: "pub85"

    profile: virtual-guest
    tuned_daemon_mode: false

    iptables_v4_custom_table_setup: ""
    iptables_v6_custom_table_setup: ""
    ip_v4_filter_custom_rule_after_ipsets: ""
    ip_v6_filter_custom_rule_after_ipsets: ""

    ipset_tables:
      - accept_ip:
        - "85.120.46.17"  # alien
        - "85.120.46.19"  # grid05
        - "85.120.46.24"  # mgm2
        - "85.120.46.25"  # mgm3
        - "85.120.46.36"  # mgm1
        - "85.120.46.40"  # seau2
      - accept_ip6:
        - "2001:b30:4210:1::17"
        - "2001:b30:4210:1::19"
        - "2001:b30:4210:1::24"
        - "2001:b30:4210:1::25"
        - "2001:b30:4210:1::36"
        - "2001:b30:4210:1::40"
      - accept_net:
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
      - accept_port_net6:
      - accept_port_tcp:
        - "2170-2172"
        - "60000"
      - accept_port_udp:

  vars_files:
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_sbdii.yml"
      - "{{ playbook_dir }}/../additions/sysctl_lists/sysctl_generic.yml"

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/pkg_utils_task.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/pkg_igtfca_task.yml"
      - "tasks/pkg_lsc_vomses_task.yml"
      - "tasks/cfg_firewall_task.yml"
      - "tasks/cfg_fail2ban_task.yml"
      - "tasks/cfg_chrony_task.yml"
      - "tasks/cfg_ssh_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/cfg_lldpd_task.yml"
      - "tasks/cfg_tuned_task.yml"
      - "tasks/cfg_gmond_misc.yml"
      - "tasks/tune_sysctl_task.yml"
      - "tasks/pkg_sbdii_task.yml"

