---
- name: Provision alice4
  hosts: alice4
  gather_facts: true
  vars:
    cvmfs_cache_size: "51200"
    cvmfs_cache_base: "/home/cvmfs/cache"
    cvmfs_repos: "cvmfs-config.cern.ch,alice.cern.ch"
    cvmfs_proxy_list: "http://issaf.spacescience.ro:3128;http://monitor.spacescience.ro:3128"

    chrony_base_ip: "priv10"

    users_create_home: false
    cluster_user_list: alice4

    profile: iss

    iptables_v4_custom_table_setup: ""
    iptables_v6_custom_table_setup: ""
    ip_v4_filter_custom_rule_after_ipsets: ""
    ip_v6_filter_custom_rule_after_ipsets: ""

    ipset_tables:
      - accept_ip:
      - accept_ip6:
      - accept_net:
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
      - accept_port_net6:
      - accept_port_tcp:
          - "22"
          - "60000"
      - accept_port_udp:

    sysctl_list:
      - "{{ playbook_dir }}/../additions/sysctl.d/60-memory.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/70-mtu.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/72-packet_tuning.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv4.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv6.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-netcore.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-fs.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-kernel.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-raid_speed.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-delayacct.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-inotify.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-security.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/80-network_buffers_1GB.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-singularity.conf"

    tuning_list:
      - "{{ playbook_dir }}/../additions/root_tuning.d/00-blockdev.tune"
      - "{{ playbook_dir }}/../additions/root_tuning.d/20-ring.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/25-channels.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/10-nic_lldp_off.tune_eth"


  vars_files:
    - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_issaf_wn.yml"
    - "{{ playbook_dir }}/../additions/root_tuning_list/tuning_generic.yml"
    - "{{ playbook_dir }}/../additions/users_cfg/{{ cluster_user_list }}/user_group_info.yml"
    - "{{ playbook_dir }}/../additions/users_cfg/{{ cluster_user_list }}/delete_users_groups.yml"

  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks:
        file: "{{ task_item }}"
      loop_control:
        loop_var: task_item
      with_items:
        - "tasks/00basic_tools.yml"
        - "tasks/00storage_tools.yml"
        - "tasks/pkg_kernelml_install_task.yml"
        - "tasks/pkg_igtfca_task.yml"
        - "tasks/pkg_lsc_vomses_task.yml"
        - "tasks/pkg_hep_oslibs_task.yml"
        - "tasks/pkg_hpc_task.yml"
        - "tasks/pkg_apptainer_task.yml"
        - "tasks/users_task.yml"
        - "tasks/cfg_firewall_task.yml"
        - "tasks/cfg_cvmfs_task.yml"
        - "tasks/cfg_chrony_task.yml"
        - "tasks/cfg_ssh_task.yml"
        - "tasks/cfg_lmsensors.yml"
        - "tasks/cfg_smartd_task.yml"
        - "tasks/cfg_lldpd_task.yml"
        - "tasks/cfg_tuned_task.yml"
        - "tasks/tune_sysctl_task.yml"
        - "tasks/tune_scripts_task.yml"
        - "tasks/pkg_utils_task.yml"
