- hosts: "{{ target | default('seau2.spacescience.ro') }}"
  gather_facts: False
  vars:
    chrony_base_ip: "pub85"

    profile: iss

    _eos_env_roles: "mgm mq fst"

    mdraid_is_enabled: "yes"
    mdraid_check_type: "check"
    mdraid_check_devs: "\"\""
    mdraid_repair_devs: "\"\""
    mdraid_skip_devs: "\"\""
    mdraid_max_concurrent: ""
    mdraid_check_time_cron: "0 0 1 * *"
    mdraid_check_time_systemd: "*-*-01 00:00:00"

    iptables_v4_custom_table_setup: ""
    iptables_v6_custom_table_setup: ""
    ip_v4_filter_custom_rule_after_ipsets: ""
    ip_v6_filter_custom_rule_after_ipsets: ""

    ipset_tables:
      - accept_ip:
      - accept_ip6:
      - accept_net:
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
      - accept_port_net6:
      - accept_port_tcp:
        - "1094"
        - "1095"
        - "60000"
      - accept_port_udp:

    cluster_user_list: seau2

  vars_files:
      - "{{ playbook_dir }}/../additions/users_{{ cluster_user_list }}/user_group_info.yml"
      - "{{ playbook_dir }}/../additions/users_{{ cluster_user_list }}/delete_users_groups.yml"
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_alien_wn.yml"
      - "{{ playbook_dir }}/../additions/sysctl_lists/sysctl_generic.yml"
      - "{{ playbook_dir }}/../additions/root_tuning_list/tuning_generic.yml"

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/00storage_tools.yml"
      - "tasks/storage_cli.yml"
      - "tasks/mdraid_conf_task.yml"
      - "tasks/seatools_sync.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/pkg_igtfca_task.yml"
      - "tasks/pkg_lsc_vomses_task.yml"
      - "tasks/pkg_eos_mgm_task.yml"
      - "tasks/pkg_eos_fst_task.yml"
      - "tasks/cfg_firewall_task.yml"
      - "tasks/cfg_fail2ban_task.yml"
      - "tasks/cfg_chrony_task.yml"
      - "tasks/cfg_ssh_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/cfg_smartd_task.yml"
      - "tasks/cfg_lldpd_task.yml"
      - "tasks/cfg_tuned_task.yml"
      - "tasks/tune_sysctl_task.yml"
      - "tasks/tune_scripts_task.yml"
      - "tasks/pkg_utils_task.yml"
      - "tasks/users_task.yml"
      - "tasks/cfg_eos_setup_task.yml"
      - "tasks/cfg_eosmgm_setup_task.yml"

