---
- hosts: "{{ target }}"
  gather_facts: False

- name: Do generic server configuration
  ansible.builtin.import_playbook: 00server_generic.yml

- name: Do IGTF certificate install
  ansible.builtin.import_playbook: igtf_certs_install.yml

- name: Install EOS rpms
  ansible.builtin.import_playbook: eos_pkg_install.yml

- name: Install mlsensor
  ansible.builtin.import_playbook: pkg_mlsensor.yml

