---
- hosts: "{{ target | default('alien.spacescience.ro') }}"
  gather_facts: False
  vars:
    cvmfs_cache_size: "51200"
    cvmfs_cache_base: "/home/cvmfs/cache"
    cvmfs_repos: "cvmfs-config.cern.ch,alice.cern.ch,alice-ocdb.cern.ch"
    cvmfs_proxy_list: "http://alien.spacescience.ro:3128;http://issaf.spacescience.ro:3128;http://monitor.spacescience.ro:3128"

    chrony_base_ip: "pub85"

    profile: iss

  vars_files:
      - "{{ playbook_dir }}/../additions/ipset/ipset_alien.yml"
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_alien_wn.yml"
      - "{{ playbook_dir }}/../additions/sysctl_lists/sysctl_generic.yml"
      - "{{ playbook_dir }}/../additions/root_tuning_list/tuning_generic.yml"
      - "{{ playbook_dir }}/../additions/users_alien/user_group_info.yml"
      - "{{ playbook_dir }}/../additions/users_alien/delete_users_groups.yml"

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/pkg_igtfca_task.yml"
      - "tasks/pkg_lsc_vomses_task.yml"
      - "tasks/pkg_hpc_task.yml"
      - "tasks/pkg_munge_task.yml"
      - "tasks/pkg_arcce_task.yml"
      - "tasks/pkg_hep_oslibs_task.yml"
      - "tasks/pkg_apptainer_task.yml"
      - "tasks/pkg_nhc_task.yml"
      - "tasks/pkg_slurm_task.yml"
      - "tasks/pkg_frontier_task.yml"
      - "tasks/users_task.yml"
      - "tasks/cfg_firewall_task.yml"
      - "tasks/cfg_cvmfs_task.yml"
      - "tasks/cfg_chrony_task.yml"
      - "tasks/cfg_ssh_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/cfg_smartd_task.yml"
      - "tasks/cfg_lldpd_task.yml"
      - "tasks/alice_ALIEN_prepare_task.yml"
      - "tasks/cfg_slurm22_task.yml"
      - "tasks/cfg_tuned_task.yml"
      - "tasks/cfg_tuning_infra.yml"
      - "tasks/tune_sysctl_task.yml"
      - "tasks/tune_scripts_task.yml"
      - "tasks/pkg_utils_task.yml"
      - "tasks/cfg_gmond_alien.yml"

