---
- hosts: "{{ target | default('issaf.spacescience.ro') }}"
  gather_facts: False
  vars:
    cvmfs_cache_size: "51200"
    cvmfs_cache_base: "/export/cvmfs/cache"
    cvmfs_repos: "cvmfs-config.cern.ch,alice.cern.ch,alice-ocdb.cern.ch"
    cvmfs_proxy_list: "http://issaf.spacescience.ro:3128;http://monitor.spacescience.ro:3128"

    chrony_base_ip: "pub46"

    users_create_home: true

    iptables_v4_custom_table_setup: ""
    iptables_v6_custom_table_setup: ""
    ip_v4_filter_custom_rule_after_ipsets: ""
    ip_v6_filter_custom_rule_after_ipsets: ""

    ipset_tables:
      - accept_ip:
      - accept_ip6:
      - accept_net:
        - "10.99.99.0/24"
      - accept_net6:
      - accept_port_ip:
      - accept_port_ip6:
      - accept_port_net:
        - "85.120.46.0/24,9090"
        - "46.243.114.128/25,9090"
        - "85.120.46.0/24,tcp:3128"
        - "46.243.114.128/25,tcp:3128"
        - "85.120.46.0/24,udp:3401"
        - "46.243.114.128/25,udp:3401"
        - "128.142.0.0/16,udp:3401"
        - "188.184.128.0/17,udp:3401"
        - "188.185.128.0/17,udp:3401"
      - accept_port_net6:
        - "2001:b30:4210::/48,9090"
        - "2001:b30:4210::/48,tcp:3128"
        - "2001:b30:4210::/48,udp:3401"
        - "2001:1458:300::/46,udp:3401"
        - "2001:1459:300::/46,udp:3401"
      - accept_port_tcp:
        - "80"
        - "443"
        - "60000"
      - accept_port_udp:

    frontier_logs: "/fastdata/frontier/logs"
    frontier_cache: "/fastdata/frontier/cache"
    frontier_allowed_networks: "10.99.99.0/24 85.120.46.0/26 46.243.114.128/25 2001:b30:4210::/48"

    profile: iss

    sysctl_list:
      - "{{ playbook_dir }}/../additions/sysctl.d/60-memory.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/70-mtu.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/72-packet_tuning.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv4.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-ipv6.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/82-netcore.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-fs.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/84-kernel.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-raid_speed.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-delayacct.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-inotify.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/99-security.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/80-network_buffers_25GB.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-singularity.conf"
      - "{{ playbook_dir }}/../additions/sysctl.d/90-frontend-forward.conf"

    tuning_list:
      - "{{ playbook_dir }}/../additions/root_tuning.d/00-blockdev.tune"
      - "{{ playbook_dir }}/../additions/root_tuning.d/00-nm_mtu.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/01-mtu_txq.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/05-fq_shape.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/20-ring.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/25-channels.tune_eth"
      - "{{ playbook_dir }}/../additions/root_tuning.d/10-nic_lldp_off.tune_eth"

  vars_files:
      - "{{ playbook_dir }}/../additions/users_issaf/user_group_info.yml"
      - "{{ playbook_dir }}/../additions/users_issaf/delete_users_groups.yml"
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_issaf_wn.yml"
      - "{{ playbook_dir }}/../additions/packages_sets/packages_issaf.yml"

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
#      - "tasks/00basic_tools.yml"
#      - "tasks/00basic_tools_hw.yml"
#      - "tasks/00storage_tools.yml"
#      - "tasks/pkg_kernelml_install_task.yml"
#      - "tasks/pkg_igtfca_task.yml"
#      - "tasks/pkg_lsc_vomses_task.yml"
#      - "tasks/pkg_hep_oslibs_task.yml"
#      - "tasks/pkg_hpc_task.yml"
#      - "tasks/pkg_munge_task.yml"
#      - "tasks/pkg_apptainer_task.yml"
#      - "tasks/pkg_nhc_task.yml"
#      - "tasks/pkg_frontier_task.yml"
#      - "tasks/users_task.yml"
#      - "tasks/cfg_firewall_task.yml"
#      - "tasks/cfg_cvmfs_task.yml"
#      - "tasks/cfg_chrony_task.yml"
#      - "tasks/cfg_ssh_task.yml"
#      - "tasks/cfg_lmsensors.yml"
#      - "tasks/cfg_smartd_task.yml"
#      - "tasks/cfg_lldpd_task.yml"
#      - "tasks/cfg_tuned_task.yml"
#      - "tasks/cfg_tuning_infra.yml"
#      - "tasks/tune_sysctl_task.yml"
#      - "tasks/tune_scripts_task.yml"
      - "tasks/pkg_utils_task.yml"
      - "tasks/packages_task.yml"
      - "tasks/pkg_alibuild_task.yml"

###      - "tasks/cfg_gmond_alien.yml"
