- hosts: "{{ target | default('eos_fst') }}"
  gather_facts: True
  vars:
    chrony_base_ip: "pub85"
    profile: iss

    _eos_env_roles: "fst"
    _eos_env_mgmhost: "mgm.spacescience.ro"
    _eos_env_mgmhosttarget: "mgm.spacescience.ro"
    _eos_env_mgm_alias: "mgm.spacescience.ro"
    _eos_env_mgm_master1: "mgm.spacescience.ro"
    _eos_env_mgm_master2: "mgm.spacescience.ro"
    _eos_env_instance: "eosalice"
    _eos_env_geotag: "ISS::ALICE"
    _eos_env_email: "glite@spacescience.ro"
    _eos_site_name: "ALICE::ISS::EOS"
    _eos_qdb_list: "mgm1.spacescience.ro:7000 mgm2.spacescience.ro:7000 mgm3.spacescience.ro:7000"
    _eos_qdb_dbdir: "/var/lib/quarkdb/qdb0"
    _eos_qdb_passfile: "/etc/quarkdb.pass"
    _eos_mgm_xrd_port: "1094"
    _eos_fst_xrd_port: "1095"
    _eos_mgm_http_port: "1094"
    _eos_fst_http_port: "1095"
    _eos_monitor_dst: "alien.spacescience.ro:9930"

    _mlsensor_vobox: "alien.spacescience.ro:8884"
    _mlsensor_se_name: "ALICE::ISS::EOS"
    _mlsensor_cluster_name_suffix: "_manager_xrootd_Services"
    _mlsensor_xrd_port_list: "1095"

    mdraid_is_enabled: "yes"
    mdraid_check_type: "check"
    mdraid_check_devs: "\"\""
    mdraid_repair_devs: "\"\""
    mdraid_skip_devs: "\"\""
    mdraid_max_concurrent: ""
    mdraid_check_time_cron: "0 0 1 * *"
    mdraid_check_time_systemd: "*-*-01 00:00:00"


  vars_files:
      - "{{ playbook_dir }}/../additions/ipset/ipset_eos.yml"
      - "{{ playbook_dir }}/../additions/ipset_blacklist/blacklist_alien_wn.yml"
      - "{{ playbook_dir }}/../additions/sysctl_lists/sysctl_generic.yml"
      - "{{ playbook_dir }}/../additions/root_tuning_list/tuning_generic.yml"

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_tools.yml"
      - "tasks/00basic_tools_hw.yml"
      - "tasks/00storage_tools.yml"
      - "tasks/storage_cli.yml"
      - "tasks/mdraid_conf_task.yml"
      - "tasks/seatools_sync.yml"
      - "tasks/pkg_kernelml_install_task.yml"
      - "tasks/pkg_igtfca_task.yml"
      - "tasks/pkg_lsc_vomses_task.yml"
      - "tasks/cfg_firewall_task.yml"
      - "tasks/cfg_chrony_task.yml"
      - "tasks/cfg_ssh_task.yml"
      - "tasks/cfg_lmsensors.yml"
      - "tasks/cfg_smartd_task.yml"
      - "tasks/cfg_lldpd_task.yml"
      - "tasks/cfg_tuned_task.yml"
      - "tasks/tune_sysctl_task.yml"
      - "tasks/tune_scripts_task.yml"
      - "tasks/cfg_gmond_eos.yml"
      - "tasks/pkg_utils_task.yml"
      - "tasks/cfg_eos_setup_task.yml"
      - "tasks/cfg_eosfst_setup_task.yml"
      - "tasks/cfg_mlsensor_task.yml"

