---
- hosts: "{{ target | default('all') }}"

  pre_tasks:
  - include_tasks: tasks/00basic_req.yml

  tasks:
  - include_tasks: tasks/00basic_hwtools.yml
  - include_tasks: tasks/smartd_cfg_task.yml

