---
- hosts: "{{ target }}"
  gather_facts: False
  tasks:
  - name: Run NHC
    ansible.builtin.raw: "nhc && echo OK || echo FAIL"
    args:
      executable: /usr/bin/bash
    register: nhc_status

#  - name: Print output
#    ansible.builtin.debug:
#      msg: "{% if command_output_on_host.rc == 0 %} {{ command_output_on_host.stdout }} {% else %} {{ command_output_on_host.stderr }} {% endif %}"

