---
- hosts: "{{ target | default('all') }}"
  gather_facts: False

  tasks:
  - ansible.builtin.include_tasks:
      file: "{{ task_item }}"
    loop_control:
      loop_var: task_item
    with_items:
      - "tasks/00basic_hwtools.yml"
      - "tasks/smartd_cfg_task.yml"
      - "tasks/00server_tools.yml"

- name: Configure mdraid check
  ansible.builtin.import_playbook: mdraid_cfg.yml

