---
- hosts: "{{ target }}"
  gather_facts: True

  vars:
    telegraf_config_url: "https://monitor.spacescience.ro:8086/api/v2/telegrafs/0aca48ef3d1f0000"

  tasks:

  # Load telegraf token
  - include_vars: "{{ playbook_dir }}/../vault/telegraf_token_https.yml"
  - include_tasks: tasks/cfg_telegraf_task.yml

