---
- hosts: "{{ target | default('all') }}"
  tasks:

  - include_tasks: tasks/00basic_req.yml

  - include_tasks: tasks/00basic_hwtools.yml

  - name: Update smartctl db from master
    ansible.builtin.command: /usr/sbin/update-smart-drivedb -u github --trunk --no-verify

  - name: Get facts
    ansible.builtin.setup:
      gather_timeout: 30
      gather_subset:
        - 'all'
        - '!facter'
        - '!ohai'

  - name: Gather extended facts
    deltabg.extended_facts.extended_facts:
      gather_timeout: 50
      gather_subset:
        - 'all'
        - '!MysqlFactCollector'
        - '!Icinga2FactCollector'
        - '!DockerFactCollector'

  # Print extended facts
  #- name: Debug
  #  debug:
  #    var: ansible_facts

