---
- hosts: "{{ target | default('all') }}"

  pre_tasks:
  - include_tasks: tasks/00basic_req.yml

  tasks:
  - include_tasks: tasks/00basic_hwtools.yml
  - include_tasks: tasks/smartd_cfg_task.yml

  post_tasks:
  - name: Get facts
    ansible.builtin.setup:
      gather_timeout: 30
      gather_subset:
        - 'all'
        - '!facter'
        - '!ohai'

  - name: Gather extended facts
    deltabg.extended_facts.extended_facts:
      gather_timeout: 50
      gather_subset:
        - 'all'
        - '!MysqlFactCollector'
        - '!Icinga2FactCollector'
        - '!DockerFactCollector'
  #  register: extd_facts

  # Print extended facts
  #- name: Debug
  #  debug:
  #    var: extd_facts.stdout

