---
- hosts: "{{ target | default('luxe') }}"
  gather_facts: False
  vars:
    cvmfs_cache_base: "/home/cvmfs/cache"
  tasks:
    - include_tasks: tasks/pkg_yum-utils_task.yml
    - include_tasks: tasks/pkg_hwmon_task.yml
    - include_tasks: tasks/pkg_lmsensors.yml
    - include_tasks: tasks/pkg_chrony.yml
    - include_tasks: tasks/pkg_gmond_task.yml
    - include_tasks: tasks/pkg_kernelml_install_task.yml
    - include_tasks: tasks/pkg_cvmfs_cache.yml

