---
- hosts: "{{ target }}"
  gather_facts: False
  tasks:
  - name: OS upgrade EL7
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version'] == '7'

  - name: OS upgrade dnf based distros
    dnf:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ( ansible_facts['distribution_major_version'] | int > 7 )
