#!/usr/bin/env bash

FST="${1}"
shift
[[ -z ${FST} ]] && { echo "ssh destination not specified"; exit 1; }

SCP="scp -3rpTOq"
RSYNC="rsync -ahuHAXW"

echo "Create script for authz keys update"
echo 'grep "$(< ~/.ssh/id_ed25519.pub.mgm)" ~/.ssh/authorized_keys &> /dev/null || cat ~/.ssh/id_ed25519.pub.mgm >> ~/.ssh/authorized_keys' > update_mgm_key
chmod +x update_mgm_key

echo "Copy mgm pub key to --> ${FST}"
${SCP} eos_mgm:/root/.ssh/id_ed25519.pub ${FST}:/root/.ssh/id_ed25519.pub.mgm

echo "upload key updating scrip"
${SCP} update_mgm_key ${FST}:/root/.ssh/ && rm -rf update_mgm_key

echo "run on fst the key updating script"
ssh ${FST} /root/.ssh/update_mgm_key

